detectors:
  BooleanParameter:
    enabled: false
  ControlParameter:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
  NilCheck:
    enabled: false
  TooManyInstanceVariables:
    max_instance_variables: 4
  UtilityFunction:
    enabled: false

exclude_paths:
  - db/
  - lib/locales/
  - vendor/
