detectors:
  BooleanParameter:
    enabled: false
  ControlParameter:
    enabled: false
  IrresponsibleModule:
    enabled: false
  NilCheck:
    enabled: false
  TooManyInstanceVariables:
    max_instance_variables: 6
  UtilityFunction:
    enabled: false
