AllCops:
  Exclude:
    - db/*
    - lib/locales/*

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  EnforcedStyle: template

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
